const SUPABASE_URL = 'https://vugtupipbpfundipgcqc.supabase.co';
const SUPABASE_KEY = 'sb_publishable_tJhW52aAlbyM_0A5_J-yqA_OTIIhV-S';

function buildReservationPageHtml(d, cssStr, headerStr, footerStr, jsStr) {
  var siteName = d.name || '업체';
  var siteId   = (d.url || d.name || '').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  var phone    = (d.phone || '').replace(/-/g, '');

  var rsvCss = [
    '.rsv-wrap{max-width:640px;margin:0 auto;padding:100px 24px 60px;}',
    '.rsv-title{font-size:clamp(24px,3vw,36px);font-weight:700;margin-bottom:8px;color:inherit;}',
    '.rsv-sub{font-size:15px;opacity:.6;margin-bottom:40px;line-height:1.6;}',
    '.rsv-form{display:flex;flex-direction:column;gap:18px;}',
    '.rsv-group{display:flex;flex-direction:column;gap:6px;}',
    '.rsv-group label{font-size:12px;letter-spacing:.1em;opacity:.6;text-transform:uppercase;font-weight:600;}',
    '.rsv-group input,.rsv-group select,.rsv-group textarea{background:#fff;border:1.5px solid rgba(0,0,0,0.15);color:#222;padding:13px 16px;font-size:15px;font-family:inherit;border-radius:4px;outline:none;transition:border-color .2s;width:100%;}',
    '.rsv-group input:focus,.rsv-group select:focus,.rsv-group textarea:focus{border-color:var(--teal,var(--rose,var(--green,#C9A040)));}',
    '.rsv-group textarea{min-height:88px;resize:vertical;}',
    '.rsv-row{display:grid;grid-template-columns:1fr 1fr;gap:16px;}',
    '.rsv-submit{padding:16px;font-size:15px;font-weight:700;font-family:inherit;background:var(--teal,var(--rose,var(--green,#C9A040)));color:#fff;border:none;cursor:pointer;border-radius:4px;transition:opacity .2s;width:100%;}',
    '.rsv-submit:hover{opacity:.85;}',
    '.rsv-submit:disabled{opacity:.5;cursor:not-allowed;}',
    '.rsv-success{display:none;text-align:center;padding:48px 24px;}',
    '.rsv-success-icon{font-size:56px;margin-bottom:16px;}',
    '.rsv-success h3{font-size:22px;margin-bottom:10px;}',
    '.rsv-success p{font-size:15px;opacity:.6;line-height:1.8;}',
    '.rsv-note{font-size:13px;opacity:.5;text-align:center;margin-top:16px;line-height:1.8;}',
    '@media(max-width:600px){.rsv-row{grid-template-columns:1fr;}}',
  ].join('');

  // 인라인 JS — 따옴표 충돌 없도록 모두 문자열 연결
  var inlineJs = [
    'var SB_URL="' + SUPABASE_URL + '";',
    'var SB_KEY="' + SUPABASE_KEY + '";',
    'var SITE_ID="' + siteId + '";',
    '',
    'async function handleRsvSubmit(){',
    '  var name=document.getElementById("rsvName").value.trim();',
    '  var phone=document.getElementById("rsvPhone").value.trim();',
    '  var date=document.getElementById("rsvDate").value;',
    '  var time=document.getElementById("rsvTime").value;',
    '  var memo=document.getElementById("rsvMemo").value.trim();',
    '  if(!name){alert("\uc774\ub984\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694.");return;}',
    '  if(!phone){alert("\uc804\ud654\ubc88\ud638\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694.");return;}',
    '  if(!date){alert("\ub0a0\uc9dc\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694.");return;}',
    '  if(!time){alert("\uc2dc\uac04\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694.");return;}',
    '  var btn=document.getElementById("rsvSubmitBtn");',
    '  btn.disabled=true;btn.textContent="\uc2e0\uccad \uc911...";',
    '  try{',
    '    var res=await fetch(SB_URL+"/rest/v1/reservations",{',
    '      method:"POST",',
    '      headers:{"Content-Type":"application/json","apikey":SB_KEY,"Authorization":"Bearer "+SB_KEY,"Prefer":"return=minimal"},',
    '      body:JSON.stringify({site_id:SITE_ID,name:name,phone:phone,date:date,time:time,memo:memo,status:"waiting"})',
    '    });',
    '    if(!res.ok){var t=await res.text();throw new Error("HTTP "+res.status+": "+t.slice(0,100));}',
    '    document.getElementById("rsvForm").style.display="none";',
    '    document.getElementById("rsvSuccess").style.display="block";',
    '  }catch(e){',
    '    alert("\uc608\uc57d \uc2e4\ud328. \uc804\ud654\ub85c \ubb38\uc758\ud574\uc8fc\uc138\uc694.\\n\uc624\ub958: "+e.message);',
    '    btn.disabled=false;btn.textContent="\uc608\uc57d \uc2e0\uccad\ud558\uae30";',
    '  }',
    '}',
    'document.getElementById("rsvDate").min=new Date().toISOString().split("T")[0];',
  ].join('\n');

  return [
    '<!DOCTYPE html>',
    '<html lang="ko">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0">',
    '<title>\uc608\uc57d\ud558\uae30 | ' + siteName + '</title>',
    cssStr ? '<style>' + cssStr + '\n' + rsvCss + '</style>' : '<style>' + rsvCss + '</style>',
    '</head>',
    '<body>',
    headerStr || '',
    '<div style="min-height:100vh;background:inherit">',
    '<div class="rsv-wrap">',
    '<div id="rsvForm">',
    '<div class="rsv-title">\uc608\uc57d\ud558\uae30</div>',
    '<div class="rsv-sub">' + siteName + '\uc5d0 \ubc29\ubb38 \uc608\uc57d\uc744 \uc2e0\uccad\ud574\uc8fc\uc138\uc694</div>',
    '<div class="rsv-form">',
    '<div class="rsv-row">',
    '<div class="rsv-group"><label>\uc774\ub984 *</label><input type="text" id="rsvName" placeholder="\ud64d\uae38\ub3d9" autocomplete="name"></div>',
    '<div class="rsv-group"><label>\uc804\ud654\ubc88\ud638 *</label><input type="tel" id="rsvPhone" placeholder="010-0000-0000" autocomplete="tel"></div>',
    '</div>',
    '<div class="rsv-row">',
    '<div class="rsv-group"><label>\uc608\uc57d \ub0a0\uc9dc *</label><input type="date" id="rsvDate"></div>',
    '<div class="rsv-group"><label>\uc608\uc57d \uc2dc\uac04 *</label>',
    '<select id="rsvTime">',
    '<option value="">\uc2dc\uac04 \uc120\ud0dd</option>',
    '<option>09:00</option><option>09:30</option><option>10:00</option><option>10:30</option>',
    '<option>11:00</option><option>11:30</option><option>12:00</option><option>13:00</option>',
    '<option>13:30</option><option>14:00</option><option>14:30</option><option>15:00</option>',
    '<option>15:30</option><option>16:00</option><option>16:30</option><option>17:00</option>',
    '<option>17:30</option><option>18:00</option><option>18:30</option><option>19:00</option>',
    '<option>19:30</option><option>20:00</option>',
    '</select></div>',
    '</div>',
    '<div class="rsv-group"><label>\ubb38\uc758 \uc0ac\ud56d (\uc120\ud0dd)</label><textarea id="rsvMemo" placeholder="\uc608\uc57d \uad00\ub828 \ubb38\uc758\uc0ac\ud56d\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694"></textarea></div>',
    '<button class="rsv-submit" id="rsvSubmitBtn" onclick="handleRsvSubmit()">\uc608\uc57d \uc2e0\uccad\ud558\uae30</button>',
    '<div class="rsv-note">\uD83D\uDCDE \uc804\ud654 \uc608\uc57d: <a href="tel:' + phone + '" style="color:inherit">' + (d.phone||'') + '</a><br>\uc608\uc57d \ud655\uc778 \ud6c4 \ub2f4\ub2f9\uc790\uac00 \uc5f0\ub77d\ub4dc\ub9bd\ub2c8\ub2e4</div>',
    '</div>',
    '</div>',
    '<div class="rsv-success" id="rsvSuccess">',
    '<div class="rsv-success-icon">\u2705</div>',
    '<h3>\uc608\uc57d \uc2e0\uccad\uc774 \uc644\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4</h3>',
    '<p>\uc785\ub825\ud558\uc2e0 \ubc88\ud638\ub85c \ud655\uc778 \uc5f0\ub77d\uc744 \ub4dc\ub9ac\uaca0\uc2b5\ub2c8\ub2e4.<br>\ubb38\uc758\uc0ac\ud56d\uc740 <a href="tel:' + phone + '" style="color:inherit">' + (d.phone||'') + '</a>\uc73c\ub85c \uc5f0\ub77d\ud574 \uc8fc\uc138\uc694.</p>',
    '<br><a href="index.html" style="display:inline-block;margin-top:16px;padding:12px 28px;background:var(--teal,var(--rose,var(--green,#C9A040)));color:#fff;text-decoration:none;font-weight:700;border-radius:4px">\ud648\uc73c\ub85c \ub3cc\uc544\uac00\uae30</a>',
    '</div>',
    '</div>',
    '</div>',
    footerStr || '',
    '<script>',
    inlineJs,
    jsStr || '',
    '<' + '/script>',
    '</body>',
    '</html>',
  ].join('\n');
}
